### ISSUE TITLE
Your discord token is public.

### ISSUE THREAD

**Issue by PvtHaggard** [01frisk00/discan#1]
Go to [discord](https://discordapp.com/developers/applications) and generate a new token for your bot.
In future do not include your tokens, private keys, or API keys in a public repo.

`INFO:discomusic:10/08/18 01:48:16AM:Bot ready`
`INFO:discomusic:10/08/18 01:48:16AM:Server: nada`
`INFO:discomusic:10/08/18 01:48:16AM:My name: Discan Demo Bot`
`INFO:discomusic:10/08/18 01:48:16AM:Admin:False`

**Comment by 01frisk00** [comment]
Was only some tests, sorry; i uploaded some time ago. I already removed it from there.
If you wanna test the package, you can install it with npm: https://www.npmjs.com/package/discan
